DROP TABLE IF EXISTS stories CASCADE;
CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  summary TEXT NOT NULL,
  date_started TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  date_completed TIMESTAMPTZ DEFAULT NULL
);
